import { useEffect, useMemo, useState } from 'react'
import './index.css'

const initialMemories = [
  { id: 1, object: 'Passport', location: 'Blue drawer', reason: 'For the trip on Friday', date: 'Oct 04', category: 'Travel', color: 'coral', pinned: true, created: '2 min ago' },
  { id: 2, object: 'Spare keys', location: 'Plant pot by the door', reason: 'For Maya when she gets home', date: 'Tonight', category: 'Home', color: 'mint', pinned: false, created: 'Yesterday' },
  { id: 3, object: 'Umbrella', location: 'Front desk', reason: 'Maria is borrowing it', date: 'Tomorrow', category: 'People', color: 'lavender', pinned: false, created: '2 days ago' },
  { id: 4, object: 'Warranty receipt', location: 'Gadget folder in Drive', reason: 'In case the blender needs replacing', date: 'No date', category: 'Paperwork', color: 'sun', pinned: false, created: '3 days ago' },
]
const categoryConfig = { Travel: { icon: '✦', color: 'coral' }, Home: { icon: '⌂', color: 'mint' }, People: { icon: '◌', color: 'lavender' }, Paperwork: { icon: '▤', color: 'sun' } }
function Icon({ name, size = 18 }) { const paths = { search: <><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/></>, plus: <><path d="M12 5v14M5 12h14"/></>, pin: <><path d="m15 4 5 5-4 1-3 3-1 4-2-2 1-4 3-3 1-4Z"/><path d="m9 15-4 4"/></>, spark: <><path d="m12 2 1.4 6.6L20 10l-6.6 1.4L12 18l-1.4-6.6L4 10l6.6-1.4L12 2Z"/><path d="m19 16 .6 2.4L22 19l-2.4.6L19 22l-.6-2.4L16 19l2.4-.6L19 16Z"/></>, arrow: <><path d="M5 12h13"/><path d="m13 6 6 6-6 6"/></>, close: <><path d="m6 6 12 12M18 6 6 18"/></>, mic: <><rect x="9" y="3" width="6" height="11" rx="3"/><path d="M5 10a7 7 0 0 0 14 0M12 17v4M8 21h8"/></> }; return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg> }
function App() {
  const [memories, setMemories] = useState(() => { try { return JSON.parse(localStorage.getItem('wdi-memories')) || initialMemories } catch { return initialMemories } })
  const [query, setQuery] = useState(''), [activeFilter, setActiveFilter] = useState('All memories'), [showCapture, setShowCapture] = useState(false), [captureText, setCaptureText] = useState(''), [toast, setToast] = useState('')
  useEffect(() => localStorage.setItem('wdi-memories', JSON.stringify(memories)), [memories])
  const filteredMemories = useMemo(() => memories.filter((memory) => { const haystack = `${memory.object} ${memory.location} ${memory.reason} ${memory.category}`.toLowerCase(); return haystack.includes(query.toLowerCase()) && (activeFilter === 'All memories' || (activeFilter === 'Pinned' ? memory.pinned : memory.category === activeFilter)) }), [memories, query, activeFilter])
  function saveMemory(event) { event.preventDefault(); if (!captureText.trim()) return; const text = captureText.trim(), object = text.split(/\s+/).slice(0, 3).join(' ').replace(/[.!?]$/, ''); setMemories((current) => [{ id: Date.now(), object: object.charAt(0).toUpperCase() + object.slice(1), location: 'Captured from your note', reason: 'Added just now', date: 'No date', category: 'Home', color: 'mint', pinned: false, created: 'Just now' }, ...current]); setCaptureText(''); setShowCapture(false); setToast('Memory saved — you can find it anytime.'); setTimeout(() => setToast(''), 3000) }
  function togglePin(id) { setMemories((current) => current.map((item) => item.id === id ? { ...item, pinned: !item.pinned } : item)) }
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><span></span><span></span><span></span></div><span>WhereDidI</span></div><div className="sidebar-label">Your memory space</div><nav className="nav-list"><button className={`nav-item ${activeFilter === 'All memories' ? 'active' : ''}`} onClick={() => setActiveFilter('All memories')}><span className="nav-icon">⌁</span> All memories <span className="count">{memories.length}</span></button><button className={`nav-item ${activeFilter === 'Pinned' ? 'active' : ''}`} onClick={() => setActiveFilter('Pinned')}><Icon name="pin" size={17}/> Pinned <span className="count">{memories.filter(m => m.pinned).length}</span></button></nav><div className="sidebar-label categories-label">Categories</div><nav className="nav-list categories">{Object.entries(categoryConfig).map(([name, config]) => <button className={`nav-item ${activeFilter === name ? 'active' : ''}`} key={name} onClick={() => setActiveFilter(name)}><span className={`category-dot ${config.color}`}>{config.icon}</span>{name}<span className="count">{memories.filter(m => m.category === name).length}</span></button>)}</nav><div className="sidebar-bottom"><div className="tip-card"><div className="tip-icon"><Icon name="spark" size={16}/></div><strong>Small things matter.</strong><p>Your future self will thank you.</p></div><button className="settings"><span>⚙</span> Settings</button><div className="profile"><div className="avatar">AK</div><div><strong>Alex Kim</strong><small>Personal space</small></div><span className="more">•••</span></div></div></aside>
    <main className="main-content"><header className="topbar"><div className="breadcrumb"><span>My space</span><span>/</span><strong>{activeFilter}</strong></div><button className="help-button">?</button></header><section className="content-inner"><div className="hero-row"><div><p className="eyebrow">YOUR EXTERNAL MEMORY</p><h1>Never lose the little things.</h1><p className="hero-copy">Capture where you put things, who has them, and why it mattered.<br className="desktop-break"/> Ask later. We’ll remember.</p></div><div className="memory-count"><span className="count-number">{memories.length}</span><span>memories<br/>kept safe</span></div></div><div className="search-wrap"><Icon name="search" size={21}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ask anything…  e.g. Where’s my passport?"/><button className="voice-button" aria-label="Voice input"><Icon name="mic" size={18}/></button><kbd>⌘ K</kbd></div><div className="quick-row"><span className="quick-label">TRY ASKING</span><button onClick={() => setQuery('passport')}>Where’s my passport?</button><button onClick={() => setQuery('borrow')}>Who has my umbrella?</button><button onClick={() => setQuery('drawer')}>What’s in the blue drawer?</button></div><div className="section-head"><div><h2>{activeFilter}</h2><p>{query ? `${filteredMemories.length} matching memories` : 'A gentle record of the things worth remembering.'}</p></div><button className="capture-button" onClick={() => setShowCapture(true)}><Icon name="plus" size={17}/> Capture a memory</button></div><div className="memory-grid">{filteredMemories.map((memory) => <article className={`memory-card ${memory.color}`} key={memory.id}><div className="card-top"><span className="memory-category"><span className={`category-dot ${memory.color}`}>{categoryConfig[memory.category]?.icon || '◌'}</span>{memory.category}</span><button className={`pin-button ${memory.pinned ? 'pinned' : ''}`} onClick={() => togglePin(memory.id)} aria-label="Pin memory"><Icon name="pin" size={16}/></button></div><h3>{memory.object}</h3><div className="detail-row"><span className="detail-icon">⌖</span><span>{memory.location}</span></div><div className="detail-row"><span className="detail-icon">✦</span><span>{memory.reason}</span></div><div className="card-footer"><span>{memory.date}</span><span>{memory.created}</span></div></article>)}{filteredMemories.length === 0 && <div className="empty-state"><div className="empty-icon"><Icon name="search" size={24}/></div><h3>No memory found</h3><p>Try a different phrase or capture something new.</p><button className="text-button" onClick={() => { setQuery(''); setShowCapture(true) }}>Capture a memory <Icon name="arrow" size={15}/></button></div>}</div><div className="bottom-quote"><span className="quote-mark">“</span><p>The things we remember are the things that make a life.</p><span className="quote-line"></span></div></section></main>
    {showCapture && <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setShowCapture(false)}><form className="capture-modal" onSubmit={saveMemory}><button type="button" className="modal-close" onClick={() => setShowCapture(false)}><Icon name="close" size={18}/></button><div className="modal-icon"><Icon name="spark" size={23}/></div><p className="eyebrow">NEW MEMORY</p><h2>What should future you remember?</h2><p className="modal-copy">Write it like you’d tell a friend. We’ll keep the important details close.</p><textarea autoFocus value={captureText} onChange={(event) => setCaptureText(event.target.value)} placeholder="I put my…" rows="4"/><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setShowCapture(false)}>Cancel</button><button className="primary-button" type="submit"><Icon name="plus" size={16}/> Save memory</button></div></form></div>}{toast && <div className="toast"><span>✓</span>{toast}</div>}
  </div>
}
export default App
